### ISSUE TITLE
Crashing on load in

### ISSUE THREAD

**Issue by WiiZy500** [q13er/gary8#10] opened 2020-05-31 02:44 UTC
Missing something with IC2, is consistent. I get in for like 5 seconds and then it go boom

[crash-2020-05-30_21.42.08-client.txt](https://github.com/q13er/gary8/files/4707018/crash-2020-05-30_21.42.08-client.txt)

**Comment by q13er** [comment] 2020-05-31 04:11
shit yeah dupe of #8

**Closed by q13er** 2020-05-31 04:11 UTC
Labels: Next Release, crash, duplicate
